# Generated by Django 5.0.1 on 2024-02-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_tic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('airport1', models.CharField(max_length=255)),
                ('airport2', models.CharField(max_length=255)),
                ('departing_date', models.DateField()),
                ('returning_date', models.DateField()),
                ('adults', models.SmallIntegerField()),
                ('Children', models.SmallIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
