# Generated by Django 5.0.1 on 2024-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_book_tic_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_tic',
        ),
    ]
