# Generated by Django 5.0.1 on 2024-02-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_remove_flight_destination_remove_flight_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='returning_date',
            field=models.DateField(),
        ),
    ]
