# Generated by Django 5.0.1 on 2024-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_flight_departing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('airport1', models.CharField(max_length=255)),
                ('airport2', models.CharField(max_length=255)),
                ('departing_date', models.DateField()),
                ('returning_date', models.DateField()),
                ('adults', models.SmallIntegerField()),
                ('Children', models.SmallIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
