# Generated by Django 5.0.1 on 2024-02-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
