# Generated by Django 5.0.1 on 2024-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_book_tic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book_tic',
            new_name='BookTickets',
        ),
    ]
