# Generated by Django 5.0.1 on 2024-02-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_rename_book_tic_booktickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktickets',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
