# Generated by Django 5.0.1 on 2024-02-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_alter_booktickets_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktickets',
            name='Children',
        ),
        migrations.AlterField(
            model_name='booktickets',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='booktickets',
            name='children',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
