# Generated by Django 5.0.1 on 2024-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_remove_booktickets_children_alter_booktickets_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktickets',
            name='departing_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booktickets',
            name='returning_date',
            field=models.CharField(max_length=200),
        ),
    ]
