# Generated by Django 5.0.1 on 2024-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
